image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install tzdata
  - apt-get -y install make grep sed gcc bison flex python git rcs cvs pylint cppcheck shellcheck

test:
  script:
  - echo "Running as ${USER:-root}"
  - make check
