image: ubuntu:latest

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get -y install make grep gcc bison flex python git cvs pylint cppcheck shellcheck

test:
  script:
  - echo "Running as ${USER:-root}"
  - make check
